[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://final-project-2-hm2d.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
